### PR TITLE
Add intepret_issue()

### PR DESCRIPTION
**Pull request by wlandau**
Interprets an issue file with a nice readable text summary. Should help with RSS feeds.

### CODE REVIEW

**Comment by shikokuchuo** [comment]
Should we use an explicit list of licenses rather than rely on the filter? It would seem that we have no control over what the filter does and/or whether it will match what our policy says.

**Comment by wlandau** [comment]
> Should we use an explicit list of licenses rather than rely on the filter? It would seem that we have no control over what the filter does and/or whether it will match what our policy says. 

For the purposes of production filters, I was concerned that a fixed list might be a bit too draconian, and it may require us to manually keep up with FOSS licenses. I was hoping to piggyback on the decades CRAN and R Core have thought about this, as well as piggyback on the automatic parsers of compound license expressions like "GPL (>= 2) | MIT + file LICENSE" (see https://cran.r-project.org/doc/manuals/R-exts.html#Licensing).

For new contributions to Community, we're forced into a fixed list for now because R does not expose its license parser for a single license string. If R Core implements https://github.com/HenrikBengtsson/Wishlist-for-R/issues/170, we can think about using it even for manual reviews. And for contributions, worst case is the package is manually reviewed, so a false positive there is no big deal.

**Comment by shikokuchuo** [comment]
Sorry I'm probably coming to these PRs in the wrong order, but I think it makes sense to have the licence check during the initial PR checks and have this flagged for moderators if non-compliant. Packages with the wrong licences should not enter Community at all - as we may not be able to distribute it.

**Comment by wlandau** [comment]
> I think it makes sense to have the licence check during the initial PR checks 

Implemented in https://github.com/r-multiverse/multiverse.internals/pull/39.

> and have this flagged for moderators if non-compliant.

Implemented in https://github.com/r-multiverse/multiverse.internals/pull/41.

> Packages with the wrong licences should not enter Community at all - as we may not be able to distribute it.

I agree, but this extra check here doesn't do any harm, and I think there are good reasons to add it:

1. The issue files in https://github.com/r-multiverse/staging/tree/main/issues will already contain R-universe check failures, security advisories, version number issues, and `Remotes:` issues. Package authors will likely assume these issue files cover everything, so omitting license problems seems like a conspicuous absence.
2. Issue files are the vehicle for the eventual RSS notification system, so if we record license issues there, subscribers will know immediately. 
3. As I explained in https://github.com/r-multiverse/multiverse.internals/pull/41#issuecomment-2494281824, package licenses can change even after they enter Community.
4. https://github.com/r-multiverse/multiverse.internals/pull/41 lists non-compliant packages, but this solution is not entirely automated. Once the list is generated, we have to look at it and manually contact the authors. I think it's much better if most license issues get automatically solved by (2) rather than straining the relationships between contributors and moderators.

**Review by shikokuchuo — APPROVED** [review]
Got it, thanks!

**Pull request merged**
